/*
 * This file was originally autogenerated by cmake, but is simpler to just keep
 * as a separate file
 */

#pragma once

#define CONFIG_SEL4RUNTIME_ROOT_STACK  16384
#define CONFIG_SEL4RUNTIME_STATIC_TLS  16384